name: comprobante
version: 1.0.0+1
publish_to: none
description: Rifa
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  crypto: ^3.0.1
  screenshot: ^1.2.3
  share_plus: ^3.0.4
  path_provider: ^2.0.6
  
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/base-rifa.png

